name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker run -d --name captcha-bot --env CAPTCHABOT_TOKEN="5224548766:AAGWjv0p28KtXLYe9j2LVYdPP9NCHZa0rmY" --restart always captcha-bot
